In [6]:
# Illustrate the powr method for computing largest eigenvector


import numpy as np
from numpy.linalg import norm

np.random.seed(0)


def power_method(A, max_iter=100, tol=1e-5):
    n = np.shape(A)[0]
    u = np.random.rand(n)
    converged = False
    iter = 0
    while (not converged) and (iter < max_iter):
        old_u = u
        u = np.dot(A, u)
        u = u / norm(u)
        lam = np.dot(u, np.dot(A, u))
        converged = norm(u - old_u) < tol
        iter += 1
    return lam, u


X = np.random.randn(10, 5)
A1 = np.dot(X.T, X)
lam1, u1 = power_method(A1)
# print(lam1,u1)
A2 = A1 -  lam1 * np.dot(u1,u1.T)
lam2, u2 = power_method(A2)
print(lam2,u2)


21.155743157371774 [-0.09948855  0.09599574  0.09602356  0.80916476  0.56295535]
-87.7864861401435 [0.46419388 0.44688679 0.45388526 0.42857859 0.44172932]


In [9]:
evals, evecs = np.linalg.eig(A)
idx = np.argsort(np.abs(evals))[::-1]  # largest first
evals = evals[idx]
evecs = evecs[:, idx]

tol = 1e-3
assert np.allclose(evecs[:, 0], u1, tol)
assert np.allclose(evals[0], lam1, tol)

idx = np.argsort(np.abs(evals))[::-2]  # 2nd largest first
evals = evals[idx]
evecs = evecs[:, idx]
print(evals)
print(evecs)
# assert np.allclose(evecs[:, 0], u2, tol)
# assert np.allclose(evals[0], lam2, tol)

[21.15574317 15.83040415  2.11083793]
[[-0.09945124  0.70060849  0.35143496]
 [ 0.09597122  0.55535464  0.08376021]
 [ 0.0959981   0.44677618 -0.67783848]
 [ 0.8091981  -0.03345173 -0.28516078]
 [ 0.56292254  0.00099077  0.57332016]]
