In [3]:
from jax import vmap
import jax.numpy as jnp

A, B, C, D = 2, 3, 4, 5
x = jnp.ones((A, B))
y = jnp.ones((B, C))
z = jnp.ones((C, D))
# print(x.shape,y.shape,z.shape)

def foo(tree_arg):
  x, (y, z) = tree_arg
  return jnp.dot(x, jnp.dot(y, z))
#   return jnp.dot(y, z)

tree = (x, (y, z))
# print(foo(tree))

K = 6  # batch size
x = jnp.ones((K, A, B))  # batch axis in different locations
y = jnp.ones((B, K, C))
z = jnp.ones((C, D, K))
print(x.shape,y.shape,z.shape)

tree = (x, (y, z))
vfoo = vmap(foo, in_axes=((0, (1, 2)),))
# print(vfoo(tree))
# print(vfoo(tree).shape)

# Another syntax
print(vmap(foo, in_axes=((0, (1, 2)),))(tree))

(6, 2, 3) (3, 6, 4) (4, 5, 6)
[[[12. 12. 12. 12. 12.]
  [12. 12. 12. 12. 12.]]

 [[12. 12. 12. 12. 12.]
  [12. 12. 12. 12. 12.]]

 [[12. 12. 12. 12. 12.]
  [12. 12. 12. 12. 12.]]

 [[12. 12. 12. 12. 12.]
  [12. 12. 12. 12. 12.]]

 [[12. 12. 12. 12. 12.]
  [12. 12. 12. 12. 12.]]

 [[12. 12. 12. 12. 12.]
  [12. 12. 12. 12. 12.]]]
