In [46]:
import numpy as np
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x.shape)
print(x)
y = np.expand_dims(x, axis=(3,1))
print(y.shape)
print(y)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 1, 5, 1)
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]
   [ 5]]]


 [[[ 6]
   [ 7]
   [ 8]
   [ 9]
   [10]]]]
