In [24]:
# calculate covariance & correlation matrix using dataset
import torch as torch
from sklearn.datasets import load_iris
iris = load_iris()
df_iris1 = torch.tensor(iris.data[:75])
df_iris2 = torch.tensor(iris.data[75:])
diffs1 = df_iris1-df_iris1.mean(dim=0)
cov_matrix_calc1 = torch.matmul(diffs1.T,diffs1)/(len(df_iris1)-1)
diffs2 = df_iris2-df_iris2.mean(dim=0)
cov_matrix_calc2 = torch.matmul(diffs1.T,diffs1)/(len(df_iris1)-1)
# print(cov_matrix_calc1)
# print(cov_matrix_calc2)
cov_11 = torch.matmul(cov_matrix_calc1.T,cov_matrix_calc1)
# print(cov_11)
cov_12 = torch.matmul(cov_matrix_calc1.T,cov_matrix_calc2)
# print(cov_12)
cov_21 = torch.matmul(cov_matrix_calc2.T,cov_matrix_calc1)
# print(cov_21)
cov_22 = torch.matmul(cov_matrix_calc2.T,cov_matrix_calc2)
# print(cov_22)
final_cov = cov_11 - torch.matmul(torch.matmul(cov_12,torch.inverse(cov_22)),cov_21)
print('----Covariance-----')
print(final_cov)
print(torch.cov(torch.tensor(iris.data).T))
print('----Mean-----')
cal_semi_mean = torch.matmul(torch.matmul(cov_12,torch.inverse(cov_22)),diffs2.T).mean(dim=1)
final_mean = df_iris1.mean(dim=0) + cal_semi_mean
print(final_mean)
print(torch.tensor(iris.data).mean(dim=0))


----Covariance-----
tensor([[ 8.6042e-14, -3.8858e-14,  2.1383e-13,  8.1934e-14],
        [-3.9008e-13,  1.9787e-13, -1.0062e-12, -3.8541e-13],
        [ 1.7106e-12, -8.6831e-13,  4.4134e-12,  1.6900e-12],
        [ 0.0000e+00, -5.5511e-17,  0.0000e+00,  0.0000e+00]],
       dtype=torch.float64)
tensor([[ 0.6857, -0.0424,  1.2743,  0.5163],
        [-0.0424,  0.1900, -0.3297, -0.1216],
        [ 1.2743, -0.3297,  3.1163,  1.2956],
        [ 0.5163, -0.1216,  1.2956,  0.5810]], dtype=torch.float64)
----Mean-----
tensor([5.3413, 3.2107, 2.4120, 0.6120], dtype=torch.float64)
tensor([5.8433, 3.0573, 3.7580, 1.1993], dtype=torch.float64)
